license:
  spdx: GPL-3.0

pipeline:
  # run unit-tests and check-cves in parallel so that a failure in unit-tests
  # doesn't stop check-cves from running
  -
    - unit-tests
    - check-cves
jobs:
  unit-tests:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-apt
      - python3-configobj
      - python3-macaroonbakery
      - python3-mock
      - python3-progressbar
      - python3-pytest
      - python3-yaml
    run-before: |
      # configure a basic ~/.ubuntu-cve-tracker.conf
      echo plb_authentication=/dev/null > ~/.ubuntu-cve-tracker.conf
    run: |
      export UCT=$(pwd)
      # some test scripts are kept outside of the scripts directory, and
      # so need PYTHONPATH set to find modules located therein
      export PYTHONPATH="${UCT}/scripts"
      # when lpcraft runs on a local users machine where embargoed already
      # exists as a symlink it won't point to anywhere so remove that and fake a
      # new one
      rm -f embargoed
      mkdir embargoed
      echo "Running unit tests..."
      pytest-3 ./scripts/test_cve_lib.py ./scripts/test_kernel_lib.py ./scripts/test_usn_lib.py ./scripts/test_publish-cves-to-website-api.py ./test/test_oval_lib_unit.py
      # ideally we would also run ./scripts/check-cves --test here as well as it
      # is more of a unit test but it requires packages-mirror so run it as part
      # of check-syntax below
  check-cves:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-apt
      - python3-configobj
      - python3-progressbar
      - python3-pytest
      - python3-yaml
      - rsync
      - wget
    run-before: |
      # configure a basic ~/.ubuntu-cve-tracker.conf and setup packages-mirror
      # for source_map
      echo plb_authentication=/dev/null > ~/.ubuntu-cve-tracker.conf
      echo "packages_mirror=$HOME/mirrors/ubuntu/" >> ~/.ubuntu-cve-tracker.conf
      for mirror in debian partner; do
        echo "${mirror}_mirror=$HOME/mirrors/${mirror}/" >> ~/.ubuntu-cve-tracker.conf
      done
      echo "Setting up packages-mirror..."
      # use wget for packages-mirror since rsync is not accessible in lp
      # builders - also invoke with -v since this seems to make downloading more
      # reliable (probably slows down wget or somesuch to it doesn't thrash the
      # internal mirror)
      echo "./scripts/packages-mirror -w -v"
      ./scripts/packages-mirror -w -v
    run: |
      export UCT=$(pwd)
      # when lpcraft runs on a local users machine where embargoed already
      # exists as a symlink it won't point to anywhere so remove that and fake a
      # new one
      rm -f embargoed
      mkdir embargoed

      ./scripts/check-cves --test
      echo "Checking syntax..."
      ./scripts/check-syntax
