license:
  spdx: GPL-3.0

pipeline: [check-syntax]
jobs:
  check-syntax:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-configobj
      - python3-yaml
      - python3-apt
      - rsync
      - wget
    run-before: |
      # configure a basic ~/.ubuntu-cve-tracker.conf and setup packages-mirror
      # for source_map
      echo packages_mirror=/root/mirrors/ubuntu/ > /root/.ubuntu-cve-tracker.conf
      for mirror in debian partner; do
        echo "${mirror}_mirror=/root/mirrors/${mirror}/" >> /root/.ubuntu-cve-tracker.conf
      done
      RELEASES="$(ubuntu-distro-info --supported)"
      RELEASES="$RELEASES $(ubuntu-distro-info --supported-esm)"
      RELEASES="$RELEASES $(ubuntu-distro-info --devel || true)"
      # since ubuntu-distro-info may not be up to date
      RELEASES="$RELEASES kinetic lunar"
      RELEASES="$(echo $RELEASES | tr ' ' '\n' | sort -u | tr '\n' ' ')"
      echo "Setting up packages-mirror for $RELEASES..."
      for release in $RELEASES; do
        echo "./scripts/packages-mirror -w -r $release"
        ./scripts/packages-mirror -r $release
        echo "./scripts/packages-mirror -w -p -r $release"
        ./scripts/packages-mirror -w -p -r $release
      done
    run: |
      echo "Checking syntax..."
      ./scripts/check-syntax
