license:
  spdx: GPL-3.0

pipeline: [check-syntax]
jobs:
  check-syntax:
    series: jammy
    architectures: amd64
    packages:
      - distro-info
      - lsb-release
      - python3
      - python3-configobj
      - python3-yaml
      - python3-apt
      - rsync
      - wget
    run-before: |
      # configure a basic ~/.ubuntu-cve-tracker.conf and setup packages-mirror
      # for source_map
      echo packages_mirror=/root/mirrors/ubuntu/ > /root/.ubuntu-cve-tracker.conf
      for mirror in debian partner; do
        echo "${mirror}_mirror=/root/mirrors/${mirror}/" >> /root/.ubuntu-cve-tracker.conf
      done
      # use the internal archive rather than the public one
      mirror=$(grep "^deb .* $(lsb_release -cs) main" /etc/apt/sources.list | awk '{print $2}' | cut -d/ -f3)
      echo "Overriding to use mirror $mirror in packages-mirror"
      sed -i s/archive.ubuntu.com/$mirror/g scripts/packages-mirror
      sed -i s/archive.canonical.com/$mirror/g scripts/packages-mirror
      RELEASES="$(ubuntu-distro-info --supported)"
      RELEASES="$RELEASES $(ubuntu-distro-info --supported-esm)"
      RELEASES="$RELEASES $(ubuntu-distro-info --devel || true)"
      # since ubuntu-distro-info may not be up to date
      RELEASES="$RELEASES kinetic lunar"
      RELEASES="$(echo $RELEASES | tr ' ' '\n' | sort -u | tr '\n' ' ')"
      echo "Setting up packages-mirror for $RELEASES..."
      for release in $RELEASES; do
        echo "Running packages-mirror for $release"
        ./scripts/packages-mirror -r $release
        ./scripts/packages-mirror -p -r $release
      done
    run: |
      ./scripts/check-syntax
